import "@/src/styles/globals.css";
import "@/src/styles/vanila.css";

import type { Metadata } from "next";
import Header from "../src/components/global/Header/Header";
import NavigationMenu from "@/src/components/global/NavigationMenu/NavigationMenu";
import AuthContextProvider from "@/src/contexts/AuthContext";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthContextProvider>
      <html lang="en">
        <body className={`relative ${inter.className}`}>
          <main className="max-w-screen-2xl mx-auto">
            <Header />
            {children}
          </main>
          {/*should be scaled up to fit with screens over w-1500px */}
        </body>
      </html>
    </AuthContextProvider>
  );
}
