import Header from "./globals/components/Header/Header";
import type { Metadata } from "next";

import "./globals/styles/globals.css";
import "./globals/styles/vanila.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="">
        <Header />
        {children}
        </main>
      </body>
    </html>
  );
}
